title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://gab-3d.github.io/gab3d-jk

aux_links:
  Template Repository: https://github.com/gab-3d/gab3d-jk/
